name: check workflow event

on:
  push:
    branches: main
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  show:
    name: show context for each event
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - run: echo "github.sha = ${{ github.sha }}"
    - run: echo "event on push to main branch"
      if: ${{ github.event.ref == 'ref/heads/main' }}
    - run: echo "event on PR merged into main branch with ${{ github.event.pull_request.head.sha }}"
      if: ${{ github.event.pull_request.merged == true && github.base_ref == 'main' }}
    - run: echo "else"
      if: ${{ github.event.ref != 'main' && (github.event.pull_request.merged != true || github.base_ref != 'main') }}
